take_snapshot:
  name: "Take Camera Snapshot"
  fields:
    camera_entity_id:
      example: "camera.cam_gewaechshaus_schnappschusse_klar"
      required: true
      selector:
        entity:
          domain: camera
    file_path:
      name: "Save Path"
      required: true
      example: "/config/www/push/snapshot.jpg"
      selector:
        text:
    file_path_backup:
      name: "Backup Save Path"
      required: true
      example: /config/www/backupsnapshots/{{ now().strftime("%y%m%d")}}_{{ now().strftime("%H%M%S")}}_snapshot.jpg
      selector:
        text:
    crop:
      example: "[500, 100, 1066, 600]"
      required: false
      selector:
        object:
    add_bar:
      name: "Add Text Bar"
      required: false
      example: true
      selector:
        boolean:
    custom_text_left:
      name: "Custom Text Left"
      required: false
      example: "Greenhouse"
      selector:
        text:
    custom_text_middle:
      name: "Custom Text Middle"
      required: false
      example: "{{ states('sensor.garten_actual_temperature') }} °C"
      selector:
        text:
    custom_text_right:
      name: "Custom Text Right"
      required: false
      example: "\"{{ now().strftime('%d.%m.%y %H:%M:%S') }}\""
      selector:
        text:
    settings:
      collaps: true
      fields:
        setting_font_path:
          example: "/config/custom_components/advanced_snapshot/fonts/Arial.ttf"
          required: false
          default: "/config/custom_components/advanced_snapshot/fonts/Arial.ttf"
          selector:
            text:
        setting_font_size:
          example: 20
          required: false
          default: 20
          selector:
            number:
              min: 1
              max: 50
              step: 2
        setting_font_color:
          example: "black"
          required: false
          default: "black"
          selector:
            text:
        setting_bar_height:
          example: 40
          required: false
          default: 40
          selector:
            number:
              min: 10
              max: 100
              step: 5
        setting_bar_color:
          example: "white"
          required: false
          default: "white"
          selector:
            text:
        setting_bar_position:
          example: "bottom"
          required: false
          default: "bottom"
          selector:
            select:
              options:
                - "top"
                - "bottom"